#!/bin/bash

#SBATCH -A sens2018122
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:00:00
#SBATCH --mail-user=maria.arceo@ki.se
#SBATCH --mail-type=ALL
#SBATCH -J xxxxx                   #### REMEMBER TO KEEP UPDATED ####
#SBATCH --output=xxxxx_%J.stdout    #### REMEMBER TO KEEP UPDATED ####
#---------------------------------------------------------------------#

dstart=$(date +"%Y/%m/%d %H:%M:%S")
SECONDS=0
#---------------------------------------------------------------------#

# Load software modules
module load bioinfo-tools
module load htseq/0.12.4
#---------------------------------------------------------------------#

# slurm arguments
if [ ! -z "$SLURM_JOB_ID" ] && [ ! "$SLURM_JOB_NAME" = "_interactive" ]
then
	START=${SLURM_ARRAY_TASK_ID}
	NUMLINES=${NUMLINES}
	STOP=$((SLURM_ARRAY_TASK_ID*NUMLINES))
	START="$(($STOP - $(($NUMLINES - 1))))"
	
	echo "JOB_NAME=${SLURM_JOB_NAME}"
	echo "JOB_ID=${SLURM_ARRAY_JOB_ID}"
	echo "TASK_ID=${SLURM_ARRAY_TASK_ID}"
	echo "LINE START=${START}"
	echo "LINE STOP=${STOP}"
fi
#-----------------------------------------------------------------------#

# EXPORTED VARIABLES
args1="${args1}"
args2="${args2}"
#-----------------------------------------------------------------------#
# Code and logs directories
codedir="${codedir}"
logdir="${logdir}/"
outdir="${outdir}/"
lognm="${lognm}"
#-----------------------------------------------------------------------#

# LOCAL VARIABLES
#-----------------------------------------------------------------------#

# Print arguments passed
var_=$( echo "$(compgen -v | grep -i args -)" )
read -d " " -a  var_array <<< "$var_"
echo "VARIABLES EXPORTED:"
for i in ${var_array[@]}
do
eval temp='$'$i
echo "$i: $temp"
done
unset var_ var_array i temp
#-----------------------------------------------------------------------#

# Run
echo "This is job ${SLURM_ARRAY_JOB_ID} task ${SLURM_ARRAY_TASK_ID}, which will do runs ${START} to ${STOP}"

for (( N = ${START}; N <= ${STOP}; N++ ))
do
	LINE=$(sed -n "$N"p ${args1})
	
	if [ ! -z "$LINE" ]
	then
		echo "This is SLURM job ${SLURM_ARRAY_JOB_ID} task ${SLURM_ARRAY_TASK_ID}, run number ${N}"
		echo "File ${LINE}"

		CELL=$( echo ${LINE%/*}  )  # keep updated
		CELL=$( echo "${CELL##*/}" )

		SAMPLE=$(echo ${LINE%/*})  # keep updated
		SAMPLE=$(echo ${SAMPLE%/*})
		SAMPLE=$( echo ${SAMPLE##*/} )

		# Create ouptut directories
		outdir1="${outdir}${SAMPLE}/${CELL}/"
		mkdir -p ${outdir1}

		# Execute
		cell=$( echo "${CELL}_R1_" )

		htseq-count --stranded=no --mode=union --nonunique=all --idattr=unique_gene_name ${LINE} ${args2} > ${outdir1}${cell}htseq.counts
	fi        
done
unset args1 args2 args3

# Checkings
oldd=$PWD

for (( N = ${START}; N <= ${STOP}; N++ ))
do
	LINE=$(sed -n "$N"p ${args1})
	
	if [ ! -z "$LINE" ]
	then
		CELL=$( echo ${LINE%/*}  )  # keep updated
		CELL=$( echo "${CELL##*/}" )

		SAMPLE=$(echo ${LINE%/*})  # keep updated
		SAMPLE=$(echo ${SAMPLE%/*})
		SAMPLE=$( echo ${SAMPLE##*/} )

		outf1="${outdir}${SAMPLE}/${CELL}/"
		
		# if file doesn't exist or exists but is empty
		if [ ! -e ${outf1}${CELL}_R1_htseq.counts ] | [ ! -s ${outf1}${CELL}_R1_htseq.counts ]
		then
			cd ${outdir}${SAMPLE}
			tar -cvzf NOTPASS-${CELL}.tar.gz ${CELL}/ && rm -r ${CELL}/
			echo "${outdir}${SAMPLE}/${CELL}" >> ${logdir}CELLS-NOTPASS
			cd $oldd
		fi
	fi
done
#-----------------------------------------------------------------------#

DURATION=$SECONDS
dend=$(date +"%Y/%m/%d %H:%M:%S")

echo "START TIME: ${dstart}"
echo "END TIME: ${dend}"
echo "RUNTIME: $(($DURATION / 3600))h $(($DURATION / 60))m $(($DURATION % 60))s"

#-----------------------------------------------------------------------#
# Collect standard output
if [ ! -z "$SLURM_JOB_ID" ] && [ ! "$SLURM_JOB_NAME" = "_interactive" ]
then
	mv ${SLURM_JOB_NAME}_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.stdout ${logdir}
	echo "LOG FILES ARE IN:"
	echo "${logdir}${SLURM_JOB_NAME}_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.stdout"
fi
