#!/bin/bash -l

#SBATCH -A sens2018122
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:00:00
#SBATCH --mail-user=maria.arceo@ki.se
#SBATCH --mail-type=ALL
#SBATCH -J 07.0_bamsCB
#SBATCH --output=07.0_bamsCB_%J.stdout 
#---------------------------------------------------------------------#

dstart=$(date +"%Y/%m/%d %H:%M:%S")
sstart=$(date +%S)
#---------------------------------------------------------------------#

# Load software modules
#module purge # cleaning
module load bioinfo-tools
module load samtools/1.20
module load java/OpenJDK_17+35
#---------------------------------------------------------------------#

# slurm arguments
if [ ! -z "$SLURM_JOB_ID" ] && [ ! "$SLURM_JOB_NAME" = "_interactive" ]
then
	START=${SLURM_ARRAY_TASK_ID}
	NUMLINES=${NUMLINES}
	STOP=$((SLURM_ARRAY_TASK_ID*NUMLINES))
	START="$(($STOP - $(($NUMLINES - 1))))"
	
	echo "JOB_NAME=${SLURM_JOB_NAME}"
	echo "JOB_ID=${SLURM_ARRAY_JOB_ID}"
	echo "TASK_ID=${SLURM_ARRAY_TASK_ID}"
	echo "LINE START=${START}"
	echo "LINE STOP=${STOP}"
fi
#-----------------------------------------------------------------------#
# EXPORTED VARIABLES
args1="${args1}"
#-----------------------------------------------------------------------#

# Code and logs directories
codedir="${codedir}"
logdir="${logdir}/"
outdir="${outdir}/"
lognm="${lognm}" 
#-----------------------------------------------------------------------#

# Print arguments passed
var_=$( echo "$(compgen -v | grep -i args -)" )
read -d " " -a  var_array <<< "$var_"
echo "VARIABLES EXPORTED:"
for i in ${var_array[@]}
do
	eval temp='$'$i
	echo "$i: $temp"
done
unset var_ var_array i temp
#-----------------------------------------------------------------------#

# Run
echo "This is job ${SLURM_ARRAY_JOB_ID} task ${SLURM_ARRAY_TASK_ID}, which will do runs ${START} to ${STOP}"

for (( N = ${START}; N <= ${STOP}; N++ ))
do
	LINE=$(sed -n "$N"p ${args1})
	
	if [ ! -z "$LINE" ]
	then
		echo "This is SLURM job ${SLURM_ARRAY_JOB_ID} task ${SLURM_ARRAY_TASK_ID}, run number ${N}"
		echo "File ${LINE}"

		CELL=$( echo ${LINE%/*}  )
		CELL=$( echo "${CELL##*/}" )

		SAMPLE=$(echo ${LINE%/*})
		SAMPLE=$(echo ${SAMPLE%/*})
		SAMPLE=$( echo ${SAMPLE##*/} )

		# Create ouptut directories
		#outdir1="${outdir}/${SAMPLE}/${CELL}/"
		#mkdir -p ${outdir1}
		
		cell=$( echo "${SAMPLE}-${CELL}" )
		
		java -jar dist/jvarkit.jar samjdk -e 'record.setAttribute("CB","${cell}");return record;' ${LINE}  2> ${outdir}${cell}.bam
	fi
done
#&done

#-----------------------------------------------------------------------#

send=$(date +%S)
dend=$(date +"%Y/%m/%d %H:%M:%S")

runtime=$((send-sstart))

echo "START TIME: ${dstart}"
echo "END TIME: ${dend}"
echo "RUNTIME: ${runtime} seconds"
#-----------------------------------------------------------------------#

# Collect standard output
if [ ! -z "$SLURM_JOB_ID" ] && [ ! "$SLURM_JOB_NAME" = "_interactive" ]
then
	mv ${SLURM_JOB_NAME}_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.stdout ${logdir}
	echo "LOG FILES ARE IN:"
	echo "${logdir}${SLURM_JOB_NAME}_${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}.stdout"
fi
